### ISSUE TITLE
Feature tracking

### ISSUE THREAD

**Issue by nulltrope** [nulltrope/thermanote#1]
# Planned Features

- [x] Basic editor functionality
- [x] Basic preview generation functionality
- [x] Basic print functionality
- [ ] Read external configuration file(s)
- [ ] Support more editor features / fonts
- [ ] Improve frontend code / templating
- [ ] Caching / CDN support
